# Generated by Django 3.2 on 2022-07-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceremony', '0002_ceremony_title_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to='media/audios'),
        ),
        migrations.AlterField(
            model_name='ceremony',
            name='title_img',
            field=models.ImageField(null=True, upload_to='media/title_images'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(upload_to='media/ceremony_images'),
        ),
    ]
