# Generated by Django 3.2 on 2022-08-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceremony', '0003_auto_20220801_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to='audios'),
        ),
    ]
